version: '3'

# Перечень volume
volumes:
  pg_data_excepto:
  static:
  media:

# Перечень контейнеров
services:
  # Имя и описание первого контейнера; имя выбирает разработчик.
  # Это контейнер БД
  db_excepto:
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data_kkin:/var/lib/postgresql/data
  # Имя и описание контейнера с бэкендом
  backend:
    # Из какого Dockerfile собирать образ для этого контейнера:
    image: tijey89/kkin_backend
    env_file: .env
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - db_kkin
    volumes:
      - static:/backend_static
      - media:/app/media
# Добавляем новый контейнер: gateway.
  gateway:
    # Сбилдить и запустить образ,
    # описанный в Dockerfile в папке gateway
    image: tijey89/kkin_gateway
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 8000 хоста
    # на порт 80 контейнера.
    volumes:
      - static:/staticfiles
      - media:/media
    ports:
      - 8000:80