FROM python:3.12

RUN apt-get update && apt-get install -y \
gettext

WORKDIR /app

RUN pip install gunicorn==20.1.0

COPY requirements.txt .

RUN pip install -r requirements.txt --no-cache-dir

COPY . .

CMD ["gunicorn", "--bind", "0.0.0.0:9000", "kkin.wsgi"]

# CMD для запуска бота
#CMD ["python", "bot.py"]