# Generated by Django 5.0.1 on 2024-01-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Координата широты города', max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='weather',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Координата долготы города', max_digits=9, null=True, verbose_name='Долгота'),
        ),
    ]
